table Location
	lineageTag: 43787e8d-c78e-4fcd-af2d-28d7110340ad

	column Province
		dataType: int64
		formatString: 0
		lineageTag: 0cc3f285-884b-41df-876e-960663934aa1
		summarizeBy: none
		sourceColumn: Province

		annotation SummarizationSetBy = Automatic

	column 'Province Name'
		dataType: string
		lineageTag: e46ac32e-05ef-4bdf-8431-74b26554d168
		summarizeBy: none
		sourceColumn: Province Name

		annotation SummarizationSetBy = Automatic

	partition Location = m
		mode: import
		source =
				let
				    Source = Pdf.Tables(File.Contents("C:\Users\msela\Documents\04_myDataProjects\LiveBirths\Recorded Live Births 1998-2024 metadata.pdf"), [Implementation="1.3"]),
				    Table015 = Source{[Id="Table015"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table015,{{"Column1", type text}, {"Column2", type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Column2", Splitter.SplitTextByEachDelimiter({"="}, QuoteStyle.None, false), {"Column2.1", "Column2.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Column2.1", type text}, {"Column2.2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type1", [PromoteAllScalars=true]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Promoted Headers",{{"11.", type text}, {"Province", Int64.Type}, {"Column3", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type2",{"11."}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Column3", "Province Name"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

